name: 배포 테스트

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

  push:
    branches:
      - 'main'

jobs:
  publish:
    runs-on: self-hosted

    env:
      HOST: 210.223.37.59
      USERNAME: tsupport
      PASSWORD: VMFfotvha5(Roqkf
      SITE_NAME: tableguide_embrain_com_dev

    steps:

    - name: whoami
      run: whoami

    - name: ssh
      run: | # Stop-Website -Name "${{ env.SITE_NAME }}"
        &"C:\sshpass.exe" -p "${{ env.PASSWORD }}" ssh ${{ env.USERNAME }}@${{ env.HOST }} "whoami && echo hello"

    - name: scp #!!rsync를 사용하세요
      run: |
        &"C:\sshpass.exe" -p "${{ env.PASSWORD }}" scp C:\test.txt ${{ env.USERNAME }}@${{ env.HOST }}:\D:\test

    - name: Checkout
      uses: actions/checkout@v6

    - name: Build
      run: dotnet build shrTest.slnx -c Release

    - name: Test
      run: dotnet test shrTest.slnx -c Release --logger "trx;LogFileName=test-results.trx"

    - name: Publish
      run: dotnet publish shrTest.slnx -c Release -o ./publish

    - name: Remove web.config
      run: Remove-Item ./publish/web.config -ErrorAction SilentlyContinue